"""Schemas for the Planner-Executor-Critic (Plan-and-Solve) pattern."""

from typing import TypedDict, List, Optional, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class Subtask(BaseModel):
    """An atomic subtask generated by the Planner."""
    task_id: str = Field(description="Unique task ID, e.g. 'task_flights', 'task_hotels', 'task_activities'")
    assigned_specialist: str = Field(description="Specialist name: 'flight_specialist', 'hotel_specialist', 'activity_specialist'")
    description: str = Field(description="Concrete actionable objective for this subtask")
    status: TaskStatus = Field(default=TaskStatus.PENDING)
    estimated_cost_usd: float = Field(default=0.0, description="Estimated cost allocation for this subtask")


class Plan(BaseModel):
    """Structured decomposition plan generated by the Planner."""
    destination: str = Field(description="Destination city / region")
    duration_days: int = Field(description="Trip duration in days")
    total_budget_limit: float = Field(description="Hard budget ceiling in USD")
    subtasks: List[Subtask] = Field(description="List of required subtasks to execute")
    strategy_notes: str = Field(description="High-level planning strategy and trade-off notes")


class CriticAuditResult(BaseModel):
    """Audit verdict produced by the Critic evaluating all worker outputs."""
    is_approved: bool = Field(description="Whether all hard constraints and budget limits are satisfied")
    total_estimated_cost_usd: float = Field(description="Sum of all selected flight, hotel, and activity costs")
    budget_surplus_or_deficit: float = Field(description="Remaining budget (>0 is surplus, <0 is deficit)")
    constraint_violations: List[str] = Field(default_factory=list, description="List of detected budget or schedule violations")
    feedback_for_planner: Optional[str] = Field(default=None, description="Actionable instructions for the planner if rejected")


class PlannerExecutorState(TypedDict):
    """Shared LangGraph state for the Planner-Executor-Critic pipeline."""
    travel_request: str
    budget_limit_usd: float
    plan: Optional[Dict[str, Any]]
    flight_results: Optional[Dict[str, Any]]
    hotel_results: Optional[Dict[str, Any]]
    activity_results: Optional[Dict[str, Any]]
    critic_audit: Optional[Dict[str, Any]]
    revision_count: int
    max_revisions: int
    final_dossier: Optional[str]
